# Generated by Django 3.1.3 on 2020-11-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_dataschemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=30, unique=True, verbose_name='Schema name')),
                ('column_separator', models.CharField(max_length=30, verbose_name='Column separator')),
                ('string_character', models.CharField(max_length=30, verbose_name='String character')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnNewSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=30, verbose_name='Column name')),
                ('type_name', models.CharField(choices=[('FN', 'Full name'), ('E', 'Email'), ('DN', 'Domain name'), ('PN', 'Phone number'), ('CN', 'Company name'), ('T', 'Text'), ('A', 'Address'), ('D', 'Date')], max_length=30, verbose_name='Type name')),
                ('from_field', models.CharField(max_length=10, verbose_name='From')),
                ('to_field', models.CharField(max_length=10, verbose_name='To')),
                ('order', models.CharField(max_length=10, verbose_name='Order')),
                ('schema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.newschema')),
            ],
        ),
        migrations.AlterField(
            model_name='dataschemas',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.newschema', to_field='schema_name'),
        ),
    ]
