# Generated by Django 3.1.3 on 2020-11-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20201114_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataschemas',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
