# Generated by Django 3.1.3 on 2020-11-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20201116_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschema',
            name='column_order',
            field=models.CharField(default=True, max_length=30, verbose_name='Column order'),
        ),
    ]
