# Generated by Django 3.1.3 on 2020-11-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_auto_20201116_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='newschema',
            name='user_id',
            field=models.CharField(default=True, max_length=30, verbose_name='User id'),
        ),
    ]
