# Generated by Django 3.1.3 on 2020-11-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_newschema_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschema',
            name='user_id',
            field=models.CharField(max_length=30, verbose_name='User id'),
        ),
    ]
