# Generated by Django 3.1.3 on 2020-11-16 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_newschema_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(default=True, max_length=30, verbose_name='Column name')),
                ('column_type', models.CharField(default=True, max_length=30, verbose_name='Column type')),
                ('column_order', models.CharField(default=True, max_length=30, verbose_name='Column order')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.newschema', to_field='schema_name')),
            ],
        ),
        migrations.RemoveField(
            model_name='newschema',
            name='column_name',
        ),
        migrations.RemoveField(
            model_name='newschema',
            name='column_order',
        ),
        migrations.RemoveField(
            model_name='newschema',
            name='column_type',
        ),
        migrations.DeleteModel(
            name='DataSchemas',
        ),
    ]
