# Generated by Django 3.1.3 on 2020-11-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_auto_20201116_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColumnNewSchema',
        ),
    ]
