# Generated by Django 3.1.3 on 2020-11-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_delete_columnnewschema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setschema',
            name='name',
        ),
        migrations.AddField(
            model_name='setschema',
            name='schema_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='generator.newschema'),
        ),
    ]
