# Generated by Django 3.1.3 on 2020-11-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0013_auto_20201117_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='setschema',
            name='set_schema',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='generator.newschema'),
        ),
    ]
