# Generated by Django 3.1.3 on 2020-11-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0014_setschema_set_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setschema',
            name='name_schema',
        ),
    ]
