# Generated by Django 3.1.3 on 2020-11-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_remove_setschema_name_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setschema',
            name='set_schema',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='generator.newschema', to_field='schema_name'),
        ),
    ]
