# Generated by Django 3.1.3 on 2020-11-17 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0016_auto_20201117_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setschema',
            name='set_schema',
        ),
        migrations.AddField(
            model_name='setschema',
            name='name_schema',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='SetSchema', to='generator.newschema'),
        ),
    ]
