# Generated by Django 3.1.3 on 2020-11-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0017_auto_20201117_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setschema',
            name='name_schema',
        ),
    ]
