# Generated by Django 3.1.3 on 2020-11-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0019_setschema_set_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschema',
            name='column_separator',
            field=models.CharField(choices=[('.', '.'), (';', ';'), (':', ':'), ('-', '-')], max_length=30, verbose_name='Column separator'),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='string_character',
            field=models.CharField(choices=[('"', '"'), ("'", "'")], max_length=30, verbose_name='String character'),
        ),
    ]
