# Generated by Django 3.1.3 on 2020-11-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0021_auto_20201118_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschema',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-11-18-07.58.09'),
        ),
        migrations.AlterField(
            model_name='setschema',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-11-18-07.58.09'),
        ),
    ]
