# Generated by Django 3.1.3 on 2020-11-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0022_auto_20201118_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschema',
            name='date',
            field=models.DateTimeField(blank=True, default='18.11.2020--08:11:29'),
        ),
        migrations.AlterField(
            model_name='setschema',
            name='date',
            field=models.DateTimeField(blank=True, default='18.11.2020--08:11:29'),
        ),
    ]
