# Generated by Django 3.1.3 on 2020-11-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0023_auto_20201118_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschema',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name=['%Y-%m-%d %H:%M:%S']),
        ),
        migrations.AlterField(
            model_name='setschema',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name=['%Y-%m-%d %H:%M:%S']),
        ),
    ]
