# Generated by Django 3.1.3 on 2020-11-18 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0024_auto_20201118_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(default=True, max_length=30, verbose_name='Schema name')),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('schema_id', models.CharField(default=True, max_length=30, verbose_name='Schema id')),
                ('set_id', models.CharField(default=True, max_length=30, verbose_name='Set id')),
            ],
            options={
                'db_table': 'Sets',
            },
        ),
        migrations.AlterField(
            model_name='newschema',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='setschema',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
