# Generated by Django 3.1.3 on 2020-11-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0026_setschema_set_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setschema',
            name='date',
            field=models.CharField(blank=True, default='11/18/2020, 10:43:50', max_length=100),
        ),
    ]
