# Generated by Django 3.1.3 on 2020-11-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0027_auto_20201118_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setschema',
            name='date',
            field=models.CharField(blank=True, default='11/18/2020--10:44:40', max_length=100),
        ),
    ]
