# Generated by Django 3.1.3 on 2020-11-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0031_auto_20201118_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sets',
            name='schema_id',
        ),
        migrations.AlterField(
            model_name='newschema',
            name='date',
            field=models.CharField(blank=True, default='11/18/2020-11:03:23', max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='data',
            field=models.CharField(blank=True, default='11/18/2020-11:03:23', max_length=100),
        ),
        migrations.AlterField(
            model_name='setschema',
            name='date',
            field=models.CharField(blank=True, default='11/18/2020-11:03:23', max_length=100),
        ),
    ]
