# Generated by Django 3.1.3 on 2020-11-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0032_auto_20201118_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='name_csv',
            field=models.CharField(default=True, max_length=30, verbose_name='Name csv-file'),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='date',
            field=models.CharField(blank=True, default='11/19/2020-09:46:23', max_length=100),
        ),
        migrations.AlterField(
            model_name='sets',
            name='data',
            field=models.CharField(blank=True, default='11/19/2020-09:46:23', max_length=100),
        ),
        migrations.AlterField(
            model_name='setschema',
            name='date',
            field=models.CharField(blank=True, default='11/19/2020-09:46:23', max_length=100),
        ),
    ]
